name: Check Flask App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get the code
        uses: actions/checkout@v3

      - name: Use Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install needed packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Try running the app
        run: |
          python -c "import app"
